<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <RootNamespace>FileLoadDemo</RootNamespace>
    <AssemblyName>FileLoadDemo</AssemblyName>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SilkAssimp\SilkAssimp.csproj"/>
    <ProjectReference Include="..\..\..\SilkToolkit\SilkToolkit.csproj" Aliases="global,WpfAssembly"/>
    <ProjectReference Include="..\DemoCore\DemoCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="5.0.0-beta1"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Images\EnvironmentMaps\Cubemap_Grandcanyon.dds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs"/>
  </ItemGroup>

</Project>
