image:
- Visual Studio 2022

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  files:
    - '*.md'

configuration: Release

before_build:
  - dotnet restore .\Source\SilkToolkit.slnx

build_script:
  - dotnet build Source\SilkToolkit.slnx --no-restore --configuration Release --no-incremental -m:1 -p:UseSharedCompilation=false -clp:ErrorsOnly