<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>

        <RootNamespace>ExampleBrowser</RootNamespace>
        <AssemblyName>ExampleBrowser</AssemblyName>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <PlatformTarget>x86</PlatformTarget>

        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="3DTools">
            <HintPath>..\..\..\..\Components\3DTools.dll</HintPath>
        </Reference>

        <Reference Include="Petzold.Media3D">
            <HintPath>..\..\..\..\Components\Petzold.Media3D.dll</HintPath>
        </Reference>

        <Reference Include="Triangle">
            <HintPath>..\..\..\..\Components\Triangle.dll</HintPath>
        </Reference>

        <Reference Include="WiimoteLib">
            <HintPath>..\..\..\..\Components\WiimoteLib.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf.Input\HelixToolkit.Wpf.Input.csproj" />
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf\HelixToolkit.Wpf.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NAudio" Version="1.10.0" />
        <PackageReference Include="NUnit" Version="4.6.0" />
        <PackageReference Include="PropertyTools.Wpf" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Images\**\*.*" />
        <Resource Include="Resources\**\*.*" />
        <Resource Include="Examples\**\*.png" />
        <Resource Include="Examples\**\*.jpg" />
        <Resource Include="Examples\**\*.jpeg" />
        <Resource Include="Examples\**\*.cur" />
        <Resource Include="Examples\**\*.ico" />
        <Resource Include="Examples\**\*.xml" />
        <Resource Include="Examples\**\*.txt" />
        <Resource Include="Examples\**\*.csv" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Examples\PanoramaDemo\Models\**\*.JPG"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="Examples\Terrain\Models\*.btz"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="Examples\Billboard\roadsign.png"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="Examples\Cloth\FlagOfNorway.png"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\..\..\models\3ds\Ferarri40.3ds"
                 Link="Examples\ModelViewer\Models\Ferarri40.3ds"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\models\3ds\LeonardoVehicle.3ds"
                 Link="Examples\ModelViewer\Models\LeonardoVehicle.3ds"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\models\3ds\Moose.3ds"
                 Link="Examples\ModelViewer\Models\Moose.3ds"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\models\obj\tour.obj"
                 Link="Examples\ModelViewer\Models\tour.obj"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\boxcube.off"
                 Link="Examples\Subdivision\Models\boxcube.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\boxtorus.off"
                 Link="Examples\Subdivision\Models\boxtorus.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\cubix.off"
                 Link="Examples\Subdivision\Models\cubix.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\epcot.off"
                 Link="Examples\Subdivision\Models\epcot.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\king.off"
                 Link="Examples\Subdivision\Models\king.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\pear.off"
                 Link="Examples\Subdivision\Models\pear.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\off\seashell.off"
                 Link="Examples\Subdivision\Models\seashell.off"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\3ds\VWBus.3ds"
                 Link="Examples\Contour\VWBus.3ds"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\3ds\Astronaut.3ds"
                 Link="Examples\CuttingPlanes\Astronaut.3ds"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
            <SubType>Designer</SubType>
        </EmbeddedResource>

        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
    </ItemGroup>
</Project>