<Project Sdk="MSBuild.Sdk.Extras/3.0.44">

    <PropertyGroup>
        <TargetFramework>uap10.0.18362</TargetFramework>
        <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>

        <OutputType>Library</OutputType>
        <RootNamespace>HelixToolkit.UWP</RootNamespace>
        <AssemblyName>HelixToolkit.UWP</AssemblyName>
        <DefaultLanguage>en-US</DefaultLanguage>

        <Platforms>AnyCPU;x86;x64;ARM</Platforms>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>

        <DefineConstants>TRACE;NETFX_CORE;WINDOWS_UWP;SHARPDX;DX11;MSAA;DX11_1</DefineConstants>

        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
        <DocumentationFile>bin\$(Platform)\$(Configuration)\HelixToolkit.UWP.xml</DocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HelixToolkit\HelixToolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.14" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="all" />
        <PackageReference Include="SharpDX" Version="4.2.0" />
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
        <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
        <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
        <PackageReference Include="System.Private.DataContractSerialization" Version="4.3.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="HelixToolkit.UWP\Resources\*.dds">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>

        <None Update="HelixToolkit.UWP\Resources\*.fnt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>

        <None Update="HelixToolkit.UWP\Resources\*.cso">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>

        <None Include="HelixToolkit.SharpDX.Shared.licenseheader" />
    </ItemGroup>

    <ItemGroup>
        <Page Update="Themes\Generic.xaml">
            <SubType>Designer</SubType>
            <Generator>MSBuild:Compile</Generator>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Page>
    </ItemGroup>

    <Import Project="..\HelixToolkit.Shared\HelixToolkit.Shared.projitems" Label="Shared" />
    <Import Project="..\HelixToolkit.SharpDX.Shared\HelixToolkit.SharpDX.Shared.projitems" Label="Shared" />
    <Import Project="..\HelixToolkit.SharpDX.SharedModel\HelixToolkit.SharpDX.SharedModel.projitems" Label="Shared" />
    <Import Project="..\HelixToolkit.UWP.Shared\HelixToolkit.UWP.Shared.projitems" Label="Shared" />

</Project>