<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelixToolkit.Wpf\HelixToolkit.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Extensions\StringExtensionsTests.cs" />
    <Compile Include="Properties\AssemblyDescription.cs" />
  </ItemGroup>
</Project>
