<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>

    <RootNamespace>MorphTargetAnimationDemo</RootNamespace>
    <AssemblyName>MorphTargetAnimationDemo</AssemblyName>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" &apos;$(Configuration)|$(Platform)&apos; == &apos;Debug|AnyCPU&apos; ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition=" &apos;$(Configuration)|$(Platform)&apos; == &apos;Release|AnyCPU&apos; ">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SilkAssimp\SilkAssimp.csproj"/>
    <ProjectReference Include="..\..\..\SilkToolkit\SilkToolkit.csproj"/>
    <ProjectReference Include="..\DemoCore\DemoCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3"/>
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Models\FBX\zophrac\source\Gunan_animated.fbx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs"/>
  </ItemGroup>

</Project>
