<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <UseWindowsForms>true</UseWindowsForms>

        <RootNamespace>CustomShaderDemo</RootNamespace>
        <AssemblyName>CustomShaderDemo</AssemblyName>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\DemoCore\DemoCore.csproj" />
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.SharpDX.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JeremyAnsel.HLSL.Targets" Version="1.0.10" />
        <PackageReference Include="PropertyTools.Wpf" Version="3.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Properties\AssemblyInfo.cs" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Shaders\Common.hlsl" />
        <Content Include="Shaders\CommonBuffers.hlsl" />
        <Content Include="Shaders\DataStructs.hlsl" />
        <Content Include="Shaders\PerlinNoise3D.hlsl" />
        <HLSLShader Include="Shaders\psMeshDataSampling.hlsl">
            <ShaderProfile>ps_4_0</ShaderProfile>
        </HLSLShader>
        <HLSLShader Include="Shaders\psMeshNoiseBlinnPhong.hlsl">
            <ShaderProfile>ps_4_0</ShaderProfile>
        </HLSLShader>
        <HLSLShader Include="Shaders\vsMeshDataSampling.hlsl">
            <ShaderProfile>vs_4_0</ShaderProfile>
        </HLSLShader>
        <HLSLShader Include="Shaders\psCustomPoint.hlsl">
            <ShaderProfile>ps_4_0</ShaderProfile>
        </HLSLShader>
    </ItemGroup>

</Project>
