<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <RootNamespace>CustomShaderDemo</RootNamespace>
    <AssemblyName>CustomShaderDemo</AssemblyName>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DemoCore\DemoCore.csproj"/>
    <ProjectReference Include="..\..\..\SilkToolkit\SilkToolkit.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Direct3D.DXC" Version="1.9.2607.13" PrivateAssets="all" GeneratePathProperty="true"/>
    <PackageReference Include="PropertyTools.Wpf" Version="3.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Shaders\Common.hlsl"/>
    <Content Include="Shaders\CommonBuffers.hlsl"/>
    <Content Include="Shaders\DataStructs.hlsl"/>
    <Content Include="Shaders\PerlinNoise3D.hlsl"/>
    <DxcShader Include="Shaders\psMeshDataSampling.hlsl">
      <ShaderProfile>ps_6_0</ShaderProfile>
    </DxcShader>
    <DxcShader Include="Shaders\psMeshNoiseBlinnPhong.hlsl">
      <ShaderProfile>ps_6_0</ShaderProfile>
    </DxcShader>
    <DxcShader Include="Shaders\vsMeshDataSampling.hlsl">
      <ShaderProfile>vs_6_0</ShaderProfile>
    </DxcShader>
    <DxcShader Include="Shaders\psCustomPoint.hlsl">
      <ShaderProfile>ps_6_0</ShaderProfile>
    </DxcShader>
  </ItemGroup>

  <Import Project="..\..\..\SilkToolkit.ShaderBuild\SilkToolkit.ShaderBuild.targets"/>

</Project>
