<Project Sdk="MSBuild.Sdk.Extras/3.0.44">

    <PropertyGroup>
        <OutputType>AppContainerExe</OutputType>

        <TargetFramework>uap10.0.18362</TargetFramework>
        <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>

        <RootNamespace>SimpleDemoW10</RootNamespace>
        <AssemblyName>SimpleDemoW10</AssemblyName>
        <DefaultLanguage>en-US</DefaultLanguage>

        <Platforms>x86;x64;ARM</Platforms>
        <RuntimeIdentifiers>win10-arm;win10-arm-aot;win10-x86;win10-x86-aot;win10-x64;win10-x64-aot</RuntimeIdentifiers>

        <DefineConstants>TRACE;NETFX_CORE;WINDOWS_UWP</DefineConstants>

        <AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>
        <PackageCertificateKeyFile>SimpleDemo_TemporaryKey.pfx</PackageCertificateKeyFile>
        <PackageCertificateThumbprint>97BA0779C1A36C6334D4D9628808C0D0E8C332A8</PackageCertificateThumbprint>

        <SignAssembly>false</SignAssembly>
        <AssemblyOriginatorKeyFile>../../../HelixToolkit.UWP.TemporaryKey.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <UseDotNetNativeToolchain>true</UseDotNetNativeToolchain>
    </PropertyGroup>

    <ItemGroup>
        <AppxManifest Include="Package.appxmanifest">
            <SubType>Designer</SubType>
        </AppxManifest>
    </ItemGroup>

    <ItemGroup>
        <Content Include="ApplicationInsights.config"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="FXT_Sparks_01_Atlas_d.png"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="Properties\Default.rd.xml" />

        <Content Include="Assets\LockScreenLogo.scale-200.png" />
        <Content Include="Assets\SplashScreen.scale-200.png" />
        <Content Include="Assets\Square150x150Logo.scale-200.png" />
        <Content Include="Assets\Square44x44Logo.scale-200.png" />
        <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
        <Content Include="Assets\StoreLogo.png" />
        <Content Include="Assets\Wide310x150Logo.scale-200.png" />

        <Content Include="..\..\..\..\Images\EnvironmentMaps\Cubemap_Grandcanyon.dds"
                 Link="Cubemap_Grandcanyon.dds"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Images\Textures\TextureCheckerboard2.jpg"
                 Link="TextureCheckerboard2.jpg"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Images\Textures\TextureCheckerboard2_dot3.jpg"
                 Link="TextureCheckerboard2_dot3.jpg"
                 CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Models\3ds\NITRO_ENGINE.3ds"
                 Link="NITRO_ENGINE.3ds"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <None Include="SimpleDemo_TemporaryKey.pfx" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\HelixToolkit.UWP\HelixToolkit.UWP.csproj" />
        <ProjectReference Include="..\..\..\HelixToolkit\HelixToolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ApplicationInsights.PersistenceChannel" Version="1.2.3" />
        <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.14" />
        <PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />
        <PackageReference Include="SharpDX" Version="4.2.0" />
        <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    </ItemGroup>

</Project>