<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWPF>true</UseWPF>

    <RootNamespace>DemoCore</RootNamespace>
    <AssemblyName>DemoCore</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="2.2.0" />
    <ProjectReference Include="..\..\..\SilkAssimp\SilkAssimp.csproj" />
    <ProjectReference Include="..\..\..\SilkToolkit\SilkToolkit.csproj" />
  </ItemGroup>

</Project>
