<Project Sdk="MSBuild.Sdk.Extras/3.0.44">

    <PropertyGroup>
        <OutputType>Library</OutputType>

        <TargetFramework>uap10.0.18362</TargetFramework>
        <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>

        <RootNamespace>HelixToolkit.UWP.Assimp</RootNamespace>
        <AssemblyName>HelixToolkit.UWP.Assimp</AssemblyName>
        <DefaultLanguage>en-US</DefaultLanguage>

        <Platforms>AnyCPU;x86;x64;ARM;ARM64</Platforms>

        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
        <GenerateLibraryLayout>true</GenerateLibraryLayout>

        <DefineConstants>TRACE;NETFX_CORE;WINDOWS_UWP;SHARPDX</DefineConstants>

        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>true</Optimize>
        <DocumentationFile>bin\$(Platform)\$(Configuration)\HelixToolkit.UWP.Assimp.xml</DocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Properties\HelixToolkit.UWP.Assimp.rd.xml" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HelixToolkit.UWP\HelixToolkit.UWP.csproj" />
        <ProjectReference Include="..\HelixToolkit\HelixToolkit.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AssimpNet" Version="5.0.0-beta1" />
        <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.2.14" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="all" />
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
        <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    </ItemGroup>

    <Import Project="..\HelixToolkit.SharpDX.Assimp.Shared\HelixToolkit.SharpDX.Assimp.Shared.projitems"
            Label="Shared" />

</Project>
