global using System.IO;
global using BindFlags = HelixToolkit.SharpDX.Core.Native.BindFlags;
global using BoundingBox = HelixToolkit.SharpDX.Core.BoundingBox;
global using BoundingFrustum = HelixToolkit.SharpDX.Core.BoundingFrustum;
global using BoundingSphere = Silk.NET.Maths.Sphere<float>;
global using Color3 = Silk.NET.Maths.Vector3D<float>;
global using Color4 = Silk.NET.Maths.Vector4D<float>;
global using CpuAccessFlags = HelixToolkit.SharpDX.Core.Native.CpuAccessFlags;
global using DataBox = HelixToolkit.SharpDX.Core.Native.DataBox;
global using Format = Silk.NET.DXGI.Format;
global using Int3 = Silk.NET.Maths.Vector3D<int>;
global using Int4 = Silk.NET.Maths.Vector4D<int>;
global using Matrix = Silk.NET.Maths.Matrix4X4<float>;
global using NativeTexture1DDescription = HelixToolkit.SharpDX.Core.Native.Texture1DDescription;
global using NativeTexture2DDescription = HelixToolkit.SharpDX.Core.Native.Texture2DDescription;
global using NativeTexture3DDescription = HelixToolkit.SharpDX.Core.Native.Texture3DDescription;
global using Plane = HelixToolkit.SharpDX.Core.Plane;
global using PointerSize = nint;
global using Quaternion = Silk.NET.Maths.Quaternion<float>;
global using Ray = HelixToolkit.SharpDX.Core.Ray;
global using ResourceOptionFlags = HelixToolkit.SharpDX.Core.Native.ResourceOptionFlags;
global using ResourceUsage = HelixToolkit.SharpDX.Core.Native.ResourceUsage;
global using SampleDescription = HelixToolkit.SharpDX.Core.Native.SampleDescription;
global using Vector2 = Silk.NET.Maths.Vector2D<float>;
global using Vector3 = Silk.NET.Maths.Vector3D<float>;
global using Vector4 = Silk.NET.Maths.Vector4D<float>;

