<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>

        <RootNamespace>SurfaceDemo</RootNamespace>
        <AssemblyName>SurfaceDemo</AssemblyName>

        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf\HelixToolkit.Wpf.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="Expressions\*.txt"
                  CopyToOutputDirectory="PreserveNewest" />

        <Resource Include="Expressions\Expressions.xml"
                  CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
            <SubType>Designer</SubType>
        </EmbeddedResource>

        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
    </ItemGroup>

</Project>
