<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>

        <RootNamespace>BatchedMeshDemo</RootNamespace>
        <AssemblyName>BatchedMeshDemo</AssemblyName>

        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\..\Models\3ds\Car.3DS"
              Link="Car.3DS"
              CopyToOutputDirectory="PreserveNewest" />

        <Content Include="..\..\..\..\Images\Textures\TextureNoise1_dot3.jpg"
                 Link="TextureNoise1_dot3.jpg"
                 CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.SharpDX.csproj" />
        <ProjectReference Include="..\DemoCore\DemoCore.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    </ItemGroup>

</Project>