<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <RootNamespace>ManipulatorDemo</RootNamespace>
    <AssemblyName>ManipulatorDemo</AssemblyName>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SilkToolkit\SilkToolkit.csproj"/>
    <ProjectReference Include="..\DemoCore\DemoCore.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expression.Interaction" Version="3.0.40218"/>
    <PackageReference Include="Fody" Version="6.9.3"/>
    <PackageReference Include="PropertyChanged.Fody" Version="4.1.0"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\..\Models\3ds\suzanne.3ds">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs"/>
  </ItemGroup>

</Project>
