<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <OutputType>Library</OutputType>
        <UseWPF>true</UseWPF>

        <RootNamespace>DemoCore</RootNamespace>
        <AssemblyName>DemoCore</AssemblyName>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.SharpDX.csproj" />
    </ItemGroup>

</Project>
