<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <RootNamespace>HelixToolkit.Wpf.SharpDX</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.0"/>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0"/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <PackageReference Include="Silk.NET.Direct2D" Version="2.23.0"/>
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.23.0"/>
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.23.0"/>
    <PackageReference Include="Silk.NET.Direct3D9" Version="2.23.0"/>
    <PackageReference Include="Silk.NET.DXGI" Version="2.23.0"/>
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0"/>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.CodeDom">
      <HintPath>$(NuGetPackageRoot)system.codedom\10.0.9\lib\net10.0\System.CodeDom.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SilkCore\SilkCore.csproj"/>
    <InternalsVisibleTo Include="SilkToolkit.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Textures\arial.dds">
      <LogicalName>SilkToolkit.Textures.arial.dds</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Textures\arial.fnt">
      <LogicalName>SilkToolkit.Textures.arial.fnt</LogicalName>
    </EmbeddedResource>
    <Page Update="Themes\Generic.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
